version: '3'

services:
  postgis:
    image: cartoview/cartoview-postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      ALLOW_IP_RANGE: 0.0.0.0/0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "pg-data-{{project_name}}:/var/lib/postgresql"
  elasticsearch:
    image: elasticsearch:2.4.1
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 2s
      timeout: 2s
      retries: 5
  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
  data-dir-conf:
    image: geonode/geoserver_data:2.14.x
    restart: on-failure
    command: /bin/true
    volumes:
      - geoserver-data-dir-{{project_name}}:/geoserver_data/data
  carto_data_dir:
    image: carto_data:latest
    restart: on-failure
    command: /bin/true
    volumes:
      - cartoview-data-{{project_name}}:/usr/src/carto_app
  geoserver:
    image: cartoview/geoserver_docker:2.14.x
    depends_on:
      - postgis
      - data-dir-conf
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/geoserver/web/ || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - "geoserver-data-dir-{{project_name}}:/geoserver_data"
    environment:
      CATALINA_OPTS: -Xmx4g -Xms2048m -XX:MaxMetaspaceSize=1024m -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:+UseParallelGC
  cartoview:
    image: cartoview/cartoview:1.10.x
    command: bash -c "python server.py"
    restart: unless-stopped
    hostname: cartoview
    depends_on:
      - postgis
      - geoserver
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
    env_file:
      - ./env/django.env
    volumes:
      - "./:/usr/src/carto_app"
  celery:
    image: cartoview/cartoview:1.10.x
    command: bash -c "celery worker --app={{project_name}} --broker=amqp://guest:guest@rabbitmq:5672/ -B -E -l debug"
    restart: unless-stopped
    hostname: celery
    depends_on:
      - postgis
      - geoserver
      - rabbitmq
    env_file:
      - ./env/django.env
    volumes:
      - "./:/usr/src/carto_app"
  nginx:
    image: cartoview/nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - cartoview
    healthcheck:
      test: ["CMD-SHELL", "curl -k --silent --fail https://localhost"]
      interval: 60s
      timeout: 15s
      retries: 10
    # volumes:
    #   - ./scripts/nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  geoserver-data-dir-{{project_name}}:
  pg-data-{{project_name}}:
  cartoview-data-{{project_name}}: